// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int32       `json:"id"`
	Name string      `json:"name"`
	Type pgtype.Text `json:"type"`
}

type Item struct {
	ID         int32          `json:"id"`
	CategoryID pgtype.Int4    `json:"category_id"`
	Sku        pgtype.Text    `json:"sku"`
	Barcode    pgtype.Text    `json:"barcode"`
	Name       string         `json:"name"`
	Type       pgtype.Text    `json:"type"`
	Unit       pgtype.Text    `json:"unit"`
	Price      pgtype.Numeric `json:"price"`
	Stock      int32          `json:"stock"`
	MinStock   pgtype.Int4    `json:"min_stock"`
	IsActive   bool           `json:"is_active"`
}
