// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    category_id,
    sku,
    barcode,
    name,
    type,
    unit,
    price,
    stock,
    min_stock,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, category_id, sku, barcode, name, type, unit, price, stock, min_stock, is_active
`

type CreateItemParams struct {
	CategoryID pgtype.Int4    `json:"category_id"`
	Sku        pgtype.Text    `json:"sku"`
	Barcode    pgtype.Text    `json:"barcode"`
	Name       string         `json:"name"`
	Type       pgtype.Text    `json:"type"`
	Unit       pgtype.Text    `json:"unit"`
	Price      pgtype.Numeric `json:"price"`
	Stock      int32          `json:"stock"`
	MinStock   pgtype.Int4    `json:"min_stock"`
	IsActive   bool           `json:"is_active"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.CategoryID,
		arg.Sku,
		arg.Barcode,
		arg.Name,
		arg.Type,
		arg.Unit,
		arg.Price,
		arg.Stock,
		arg.MinStock,
		arg.IsActive,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.Price,
		&i.Stock,
		&i.MinStock,
		&i.IsActive,
	)
	return i, err
}

const findItemByID = `-- name: FindItemByID :one
SELECT id, category_id, sku, barcode, name, type, unit, price, stock, min_stock, is_active from items WHERE id = $1
`

func (q *Queries) FindItemByID(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRow(ctx, findItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.Price,
		&i.Stock,
		&i.MinStock,
		&i.IsActive,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type from categories
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, category_id, sku, barcode, name, type, unit, price, stock, min_stock, is_active from items
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Sku,
			&i.Barcode,
			&i.Name,
			&i.Type,
			&i.Unit,
			&i.Price,
			&i.Stock,
			&i.MinStock,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
