// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	FindItemByID(ctx context.Context, id int32) (Item, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListItems(ctx context.Context) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
